# Generated by Django 6.1 on 2026-08-12 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultoResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Adulto Responsable',
                'verbose_name_plural': 'Adultos Responsables',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_riesgo', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_termino', models.DateTimeField(blank=True, help_text="Se rellena automáticamente al guardar el mensaje de tipo 'end'", null=True)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje', models.FloatField(default=0.0, help_text='Puntaje calculado en base a las respuestas del jugador')),
            ],
            options={
                'verbose_name': 'Nivel de Riesgo',
                'verbose_name_plural': 'Niveles de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('aliado', 'Aliado'), ('neutral', 'Neutral'), ('enemigo', 'Enemigo')], default='neutral', max_length=20)),
                ('confianza', models.IntegerField(default=0, help_text='Nivel de confianza del NPC hacia el jugador (ej: 0-100)')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
            },
        ),
        migrations.CreateModel(
            name='PreguntaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_id', models.CharField(max_length=60, unique=True)),
                ('hdu', models.CharField(max_length=10)),
                ('zona', models.CharField(max_length=50)),
                ('npc_id', models.CharField(blank=True, max_length=30)),
                ('npc_nombre', models.CharField(blank=True, max_length=60)),
                ('npc_avatar', models.CharField(blank=True, max_length=60)),
                ('fase', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('orden_en_fase', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('narrativa_continuacion', models.CharField(blank=True, max_length=60, null=True)),
                ('escenario_id', models.CharField(blank=True, max_length=60)),
                ('escenario_nombre', models.CharField(blank=True, max_length=120)),
                ('historial_previo', models.JSONField(default=list)),
                ('categoria', models.CharField(max_length=60)),
                ('nivel_riesgo', models.PositiveSmallIntegerField(default=0)),
                ('es_mensaje_riesgo', models.BooleanField(default=False)),
                ('mensaje_npc', models.TextField()),
                ('etiquetas_ml', models.JSONField(default=list)),
                ('es_fin_de_npc', models.BooleanField(default=False, help_text='True en estados FIN_SEGURO / FIN_INSEGURO')),
                ('es_fin_de_zona', models.BooleanField(default=False, help_text='True en la pregunta ZONA_FIN')),
            ],
            options={
                'verbose_name': 'Pregunta Banco',
                'verbose_name_plural': 'Preguntas Banco',
                'ordering': ['zona', 'npc_id', 'fase', 'orden_en_fase', 'escenario_id'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('start', 'Start'), ('chain', 'Chain'), ('request', 'Request'), ('end', 'End')], max_length=10)),
                ('respuesta', models.TextField()),
                ('calidad_respuesta', models.CharField(blank=True, choices=[('buena', 'Buena'), ('neutral', 'Neutral'), ('mala', 'Mala')], max_length=10)),
                ('pregunta_banco_id', models.CharField(blank=True, help_text='ID de la pregunta del banco que originó este mensaje (ej: HDU2_NPC01_F2_Q01).', max_length=70, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='api.chat')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.npc'),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.FloatField(default=0.0, help_text='Porcentaje de progreso (0-100)')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('nivel_riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='api.nivelriesgo')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.AddField(
            model_name='npc',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='api.partida'),
        ),
        migrations.AddField(
            model_name='chat',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.partida'),
        ),
        migrations.CreateModel(
            name='PersonajeJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personaje', to='api.partida')),
            ],
            options={
                'verbose_name': 'Personaje Jugador',
                'verbose_name_plural': 'Personajes Jugador',
            },
        ),
        migrations.CreateModel(
            name='PosibleRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de presentación al jugador')),
                ('calidad_respuesta', models.CharField(blank=True, choices=[('buena', 'Buena'), ('neutral', 'Neutral'), ('mala', 'Mala')], help_text='Calidad asociada a esta opción de respuesta', max_length=10)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posibles_respuestas', to='api.mensaje')),
            ],
            options={
                'verbose_name': 'Posible Respuesta',
                'verbose_name_plural': 'Posibles Respuestas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_id', models.CharField(max_length=70, unique=True)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('consecuencia_narrativa', models.TextField()),
                ('impacto_puntuacion', models.SmallIntegerField(default=0)),
                ('siguiente_pregunta', models.CharField(blank=True, max_length=60, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='api.preguntabanco')),
            ],
            options={
                'verbose_name': 'Opción Banco',
                'verbose_name_plural': 'Opciones Banco',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('adulto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Jugador',
                'verbose_name_plural': 'Usuarios Jugadores',
            },
        ),
        migrations.AddField(
            model_name='partida',
            name='usuario_jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='api.usuariojugador'),
        ),
        migrations.AddConstraint(
            model_name='usuariojugador',
            constraint=models.UniqueConstraint(fields=('adulto', 'nombre'), name='jugador_unico_por_adulto'),
        ),
    ]
