# Generated by Django 6.0.6 on 2026-06-03 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_riesgo', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nivel de Riesgo',
                'verbose_name_plural': 'Niveles de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('aliado', 'Aliado'), ('neutral', 'Neutral'), ('enemigo', 'Enemigo')], default='neutral', max_length=20)),
                ('confianza', models.IntegerField(default=0, help_text='Nivel de confianza del NPC hacia el jugador (ej: 0-100)')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('jugador', 'Jugador'), ('npc', 'NPC')], max_length=10)),
                ('respuesta', models.TextField()),
                ('calidad_respuesta', models.CharField(blank=True, choices=[('buena', 'Buena'), ('neutral', 'Neutral'), ('mala', 'Mala')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='api.chat')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.npc'),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.FloatField(default=0.0, help_text='Porcentaje de progreso (0-100)')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('nivel_riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='api.nivelriesgo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.AddField(
            model_name='npc',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='api.partida'),
        ),
        migrations.AddField(
            model_name='chat',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.partida'),
        ),
        migrations.CreateModel(
            name='PersonajeJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personaje', to='api.partida')),
            ],
            options={
                'verbose_name': 'Personaje Jugador',
                'verbose_name_plural': 'Personajes Jugador',
            },
        ),
        migrations.CreateModel(
            name='PosibleRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de presentación al jugador')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posibles_respuestas', to='api.mensaje')),
            ],
            options={
                'verbose_name': 'Posible Respuesta',
                'verbose_name_plural': 'Posibles Respuestas',
                'ordering': ['orden'],
            },
        ),
    ]
