# Generated by Django 6.0.6 on 2026-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, help_text="Se rellena automáticamente al guardar el mensaje de tipo 'end'", null=True),
        ),
        migrations.AddField(
            model_name='nivelriesgo',
            name='puntaje',
            field=models.FloatField(default=0.0, help_text='Puntaje calculado en base a las respuestas del jugador'),
        ),
        migrations.AddField(
            model_name='posiblerespuesta',
            name='calidad_respuesta',
            field=models.CharField(blank=True, choices=[('buena', 'Buena'), ('neutral', 'Neutral'), ('mala', 'Mala')], help_text='Calidad asociada a esta opción de respuesta', max_length=10),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('start', 'Start'), ('chain', 'Chain'), ('request', 'Request'), ('end', 'End')], max_length=10),
        ),
    ]
