# Generated by Django 6.1 on 2026-08-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='opcion_banco_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de la opción del banco que eligió el jugador (ej: HDU2_NPC01_F2_Q01_R2). Es la llave que permite acumular riesgo por zona: se resuelve contra OpcionBanco para obtener impacto_puntuacion y la zona de su pregunta.', max_length=70, null=True),
        ),
    ]
