# Generated by Django 6.1 on 2026-09-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_detective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision_id', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(blank=True, help_text='`nombre_mision` del banco. La de exploracion no trae nombre.', max_length=120)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('secundaria', 'Secundaria'), ('exploracion', 'Exploracion')], default='secundaria', max_length=20)),
                ('zona', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Mision',
                'verbose_name_plural': 'Misiones',
                'ordering': ['zona', 'mision_id'],
            },
        ),
        migrations.CreateModel(
            name='DialogoNPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogo_id', models.CharField(max_length=60, unique=True)),
                ('hdu', models.CharField(max_length=10)),
                ('zona', models.CharField(max_length=50)),
                ('npc_id', models.CharField(blank=True, max_length=30)),
                ('npc_nombre', models.CharField(blank=True, max_length=60)),
                ('npc_avatar', models.CharField(blank=True, max_length=60)),
                ('tipo', models.CharField(blank=True, help_text='`neutro` en todos los del banco actual', max_length=20)),
                ('trigger', models.CharField(blank=True, help_text='Como se dispara en el juego, ej. `boton_E`', max_length=30)),
                ('lineas', models.JSONField(default=list, help_text='Lista de strings, en orden de aparicion')),
                ('pista_mision', models.TextField(blank=True, null=True)),
                ('mision', models.ForeignKey(blank=True, help_text='Mision que este dialogo desbloquea (`mision_desbloquea`)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogos', to='api.mision')),
            ],
            options={
                'verbose_name': 'Dialogo NPC',
                'verbose_name_plural': 'Dialogos NPC',
                'ordering': ['zona', 'dialogo_id'],
            },
        ),
        migrations.CreateModel(
            name='RecompensaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recompensa_id', models.CharField(max_length=90, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tip_educativo', models.TextField(blank=True, help_text='El tip entre parentesis, cuando el banco lo trae')),
                ('opcion_banco_id', models.CharField(blank=True, db_index=True, default='', help_text='`opcion_id` de la OpcionBanco que la entrega. Es texto y no FK a proposito: cargar_banco borra y recrea las opciones en cada corrida, asi que una FK real se llevaria en cascada el album ya obtenido por los ninos. Mismo criterio que Mensaje.opcion_banco_id.', max_length=70)),
                ('mision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to='api.mision')),
            ],
            options={
                'verbose_name': 'Recompensa de Album',
                'verbose_name_plural': 'Recompensas de Album',
                'ordering': ['recompensa_id'],
            },
        ),
        migrations.CreateModel(
            name='RecompensaObtenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_album', to='api.partida')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obtenciones', to='api.recompensaalbum')),
            ],
            options={
                'verbose_name': 'Recompensa Obtenida',
                'verbose_name_plural': 'Recompensas Obtenidas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='recompensaalbum',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mision__isnull', False), ('opcion_banco_id', '')), models.Q(('mision__isnull', True), models.Q(('opcion_banco_id', ''), _negated=True)), _connector='OR'), name='recompensa_con_un_solo_origen'),
        ),
        migrations.AddConstraint(
            model_name='recompensaobtenida',
            constraint=models.UniqueConstraint(fields=('partida', 'recompensa'), name='recompensa_unica_por_partida'),
        ),
    ]
