# Generated by Django 6.1 on 2026-09-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_catalogo_misiones_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision_id', models.CharField(db_index=True, help_text='`desafioId` del DesafioData de Unity / `mision_id` del banco, ej. MISION_NPC_01', max_length=60)),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='api.partida')),
            ],
            options={
                'verbose_name': 'Progreso de Mision',
                'verbose_name_plural': 'Progreso de Misiones',
                'ordering': ['partida', 'fecha_desbloqueo'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'mision_id'), name='mision_unica_por_partida')],
            },
        ),
        migrations.CreateModel(
            name='ZonaProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(db_index=True, help_text='Slug de la zona del banco, ej. `ciberacoso`', max_length=50)),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='api.partida')),
            ],
            options={
                'verbose_name': 'Progreso de Zona',
                'verbose_name_plural': 'Progreso de Zonas',
                'ordering': ['partida', 'zona'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'zona'), name='zona_unica_por_partida')],
            },
        ),
    ]
