# Generated by Django 6.1 on 2026-08-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mensaje_pregunta_banco_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_id',
            field=models.CharField(blank=True, help_text='Sub (subject id) de la cuenta de Google, si el usuario inicio sesion con Google.', max_length=255, null=True, unique=True),
        ),
    ]
