# Generated by Django 6.1 on 2026-09-06 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_zona_inicial_en_partidas_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, help_text='`itemId` del ItemData de Unity, ej. ITEM_BRUJULA', max_length=60)),
                ('cantidad', models.PositiveSmallIntegerField(default=1, help_text='Unidades que lleva encima. Una fila en 0 no se guarda: se borra.')),
                ('fecha_primera_vez', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.partida')),
            ],
            options={
                'verbose_name': 'Item del inventario',
                'verbose_name_plural': 'Inventario',
                'ordering': ['partida', 'item_id'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'item_id'), name='item_unico_por_partida')],
            },
        ),
    ]
