# Generated by Django 6.1 on 2026-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_iteminventario_fecha_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajejugador',
            name='escena',
            field=models.CharField(blank=True, help_text='Escena de Unity donde estaba, ej. `SampleScene`. Se guarda para no restaurar una posicion de otra escena si algun dia hay mas de una.', max_length=80),
        ),
        migrations.AddField(
            model_name='personajejugador',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personajejugador',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personajejugador',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
