# Generated by Django 6.1 on 2026-09-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_personaje_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoRecogido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_id', models.CharField(db_index=True, help_text='`objetoId` del WorldItem de la escena, ej. SAMPLESCENE_CONCHA_01', max_length=80)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_recogidos', to='api.partida')),
            ],
            options={
                'verbose_name': 'Objeto recogido',
                'verbose_name_plural': 'Objetos recogidos',
                'ordering': ['partida', 'objeto_id'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'objeto_id'), name='objeto_unico_por_partida')],
            },
        ),
    ]
