# Generated by Django 6.1 on 2026-09-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_objetos_recogidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpcProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_id', models.CharField(db_index=True, help_text='`npcId` del NPC en la escena, ej. BOSQUE_DESCONOCIDO_01', max_length=80)),
                ('exito', models.BooleanField(default=False, help_text="El nino/a supero el umbral de respuestas seguras de ese NPC. Decide si el NPC se retira del mapa y si cuenta como 'a salvo'.")),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_npcs', to='api.partida')),
            ],
            options={
                'verbose_name': 'Progreso de NPC',
                'verbose_name_plural': 'Progreso de NPCs',
                'ordering': ['partida', 'npc_id'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'npc_id'), name='npc_unico_por_partida')],
            },
        ),
    ]
