# Generated by Django 6.1 on 2026-09-11 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_progreso_npcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=280)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_invitado', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='api.grupotutor')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='api.usuariojugador')),
            ],
        ),
        migrations.CreateModel(
            name='InvitacionGrupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_nino', models.CharField(max_length=150)),
                ('nombre_clave', models.CharField(max_length=450)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12)),
                ('estado_envio', models.CharField(choices=[('enviando', 'Enviando'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='enviando', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_intento', models.DateTimeField()),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('vence_en', models.DateTimeField()),
                ('aceptada_en', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='api.grupotutor')),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones', to='api.miembrogrupo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='miembrogrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'jugador'), name='miembro_unico_por_grupo_jugador'),
        ),
        migrations.AddConstraint(
            model_name='invitaciongrupo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('grupo', 'email', 'nombre_clave'), name='invitacion_pendiente_unica_por_nino'),
        ),
    ]
