# Generated by Django 6.1 on 2026-09-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_progreso_npcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajejugador',
            name='zona_actual',
            field=models.CharField(blank=True, help_text='Zona del mapa donde quedo Otto, ej. `zona_2`. Es el `zoneId` de la BlockedZone de Unity, NO el slug del banco que usa ZonaProgreso.zona.', max_length=50),
        ),
    ]
