# Generated by Django 6.1 on 2026-09-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_personaje_zona_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultoresponsable',
            name='rol',
            field=models.CharField(choices=[('padre', 'Padre o madre'), ('profesor', 'Profesor')], db_default='padre', default='padre', max_length=10),
        ),
    ]
