# Generated by Django 6.1 on 2026-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_grupos_invitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodetective',
            name='recompensa_accesorio_hdu06',
            field=models.CharField(blank=True, db_default='', default='', max_length=150),
        ),
        migrations.AddField(
            model_name='casodetective',
            name='recompensa_item_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=60),
        ),
        migrations.AddField(
            model_name='casodetective',
            name='recompensa_no_duplica_al_repetir',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='casodetective',
            name='recompensa_nombre',
            field=models.CharField(blank=True, db_default='', default='', max_length=150),
        ),
        migrations.AddField(
            model_name='casodetective',
            name='recompensa_umbral_aciertos',
            field=models.FloatField(db_default=0.5, default=0.5),
        ),
    ]
