# Generated by Django 6.1 on 2026-09-17 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_recompensa_caso_detective'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='desbloquea_mision',
            field=models.CharField(blank=True, db_default='', default='', help_text='`mision_id` de la mision que se entrega sola al completar esta. Es texto y no FK a proposito: los ids del catalogo no son estables y hay que poder reemplazar una mision sin que una FK se lleve nada por delante. Vacio = no encadena.', max_length=60),
        ),
        migrations.AddField(
            model_name='mision',
            name='descripcion',
            field=models.TextField(blank=True, db_default='', default='', help_text='Texto fijo que REEMPLAZA a la lista de objetivos en el panel. Vacio = se listan los objetivos.'),
        ),
        migrations.AddField(
            model_name='mision',
            name='orden',
            field=models.IntegerField(db_default=100, default=100, help_text='Lugar en la historia; menor va antes. Es una suposicion del archivo, NO el orden narrativo confirmado.'),
        ),
        migrations.AddField(
            model_name='mision',
            name='recompensa_cantidad',
            field=models.IntegerField(db_default=0, default=0, help_text='Unidades de `recompensa_item_id`. 0 o negativo lo trata Unity como 1.'),
        ),
        migrations.AddField(
            model_name='mision',
            name='recompensa_item_id',
            field=models.CharField(blank=True, db_default='', default='', help_text='ItemData que se entrega al completar. Vacio = sin recompensa automatica.', max_length=60),
        ),
        migrations.AddField(
            model_name='mision',
            name='zona_objetivo',
            field=models.CharField(blank=True, db_default='', default='', help_text='Zona ESPACIAL de destino (`zona_1`...), no la tematica del banco. Ver ZonaProgreso.', max_length=50),
        ),
        migrations.CreateModel(
            name='ObjetivoMision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='Estable una vez publicado: es la mitad de la clave con la que se guarda el avance.')),
                ('tipo', models.CharField(choices=[('recoger_objeto', 'Recoger objeto'), ('hablar_npc', 'Hablar con un NPC'), ('chatear_telefono', 'Chatear por telefono'), ('llegar_zona', 'Llegar a una zona'), ('completar_caso_detective', 'Completar un caso Detective')], help_text='Va en texto y no como indice: el enum de Unity se puede reordenar.', max_length=30)),
                ('item_id', models.CharField(blank=True, default='', help_text='recoger_objeto', max_length=60)),
                ('cantidad', models.IntegerField(default=1, help_text='recoger_objeto. El avance NO se guarda: se recalcula del inventario.')),
                ('dialogo_id', models.CharField(blank=True, default='', help_text='hablar_npc', max_length=60)),
                ('escenario_ids', models.CharField(blank=True, default='', help_text='chatear_telefono; varios separados por coma', max_length=200)),
                ('zona_id', models.CharField(blank=True, default='', help_text='llegar_zona; id ESPACIAL', max_length=50)),
                ('caso_id', models.CharField(blank=True, default='', help_text='completar_caso_detective', max_length=60)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Texto fijo para el panel; vacio = lo arma Unity', max_length=200)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='api.mision')),
            ],
            options={
                'verbose_name': 'Objetivo de Mision',
                'verbose_name_plural': 'Objetivos de Mision',
                'ordering': ['mision', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('mision', 'orden'), name='objetivo_unico_por_mision')],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision_id', models.CharField(db_index=True, max_length=60)),
                ('orden', models.IntegerField()),
                ('cumplido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='api.partida')),
            ],
            options={
                'verbose_name': 'Progreso de Objetivo',
                'verbose_name_plural': 'Progreso de Objetivos',
                'ordering': ['partida', 'mision_id', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'mision_id', 'orden'), name='objetivo_unico_por_partida')],
            },
        ),
    ]
