# Generated by Django 6.1 on 2026-09-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_catalogo_misiones_y_objetivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultoresponsable',
            name='rol',
            field=models.CharField(choices=[('padre', 'Padre o madre'), ('profesor', 'Profesor'), ('admin', 'Admin del portal (equipo)')], db_default='padre', default='padre', max_length=10),
        ),
    ]
