# Generated by Django 6.1 on 2026-09-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_adulto_rol_admin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='miembrogrupo',
            name='miembro_unico_por_grupo_jugador',
        ),
        migrations.AddConstraint(
            model_name='miembrogrupo',
            constraint=models.UniqueConstraint(fields=('jugador',), name='miembro_un_curso_por_jugador'),
        ),
    ]
