# Generated by Django 6.1 on 2026-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_miembro_un_curso_por_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntabanco',
            name='pensamiento_otto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
