# Generated by Django 6.1 on 2026-10-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_pregunta_pensamiento_otto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recompensaalbum',
            name='recompensa_con_un_solo_origen',
        ),
        migrations.AddField(
            model_name='recompensaalbum',
            name='final_id',
            field=models.CharField(blank=True, default='', help_text='`id` del final (FINAL_A/B/C) que la entrega. La medalla depende del puntaje de toda la aventura, no de la opcion que se elija en la Mision 6.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='recompensaalbum',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('final_id', ''), ('mision__isnull', False), ('opcion_banco_id', '')), models.Q(('final_id', ''), ('mision__isnull', True), models.Q(('opcion_banco_id', ''), _negated=True)), models.Q(('mision__isnull', True), ('opcion_banco_id', ''), models.Q(('final_id', ''), _negated=True)), _connector='OR'), name='recompensa_con_un_solo_origen'),
        ),
    ]
